### ISSUE TITLE
Add a command line switch to display sparse matrices with periods (.) replacing zero elements (0). 

### ISSUE THREAD

**Issue by dde** [dde/qqcs#18]
The pattern of the non-zero entries in a matrix display of a sparse matrix can be seen more clearly if periods are displayed in place of zero-entries.

**Comment by WingCode** [comment]
@dde I would like to try adding this feature

**Comment by dde** [comment]
Great! Please go ahead.

**Comment by dde** [comment]
I was examining some of the details of your change.  For future changes, note that one of the standard Javascript coding conventions is to "avoid polluting the global namespace."  The global variable you introduced, configReplaceZeroes, would have been better implemented as a property of the SpMatrix constructor accessed with a toggle method.  And since CMatrix and SpMatrix can be used equivalently, also added to CMatrix.  It's not a big deal and I will leave the issue closed.  I'm making some other changes, and will just incorporate that.
